Repository apache/jena, pull requests merged in 2022-11, with the labels that each got.

#1610 Fixes prototype pollution issue in webpack loader-utils
  jena-fuseki2/jena-fuseki-ui/package.json
  jena-fuseki2/jena-fuseki-ui/yarn.lock
Labels: dependencies, javascript

#1625 Bump loader-utils from 1.4.1 to 1.4.2. Rebuild yarn.lock
  jena-fuseki2/jena-fuseki-ui/package.json
  jena-fuseki2/jena-fuseki-ui/yarn.lock
Labels: dependencies, javascript

#1632 Update Apache parent POM version from 27 to 28
  pom.xml
Labels: dependencies

#1620 Allow toggling extended path flattening on
  jena-arq/src/main/java/org/apache/jena/query/ARQ.java
  jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/OptimizerStd.java
  jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformMergeBGPs.java
  jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformPathFlattenAlgebra.java
  jena-arq/src/main/java/org/apache/jena/sparql/path/PathCompiler.java
  jena-arq/src/test/java/org/apache/jena/sparql/algebra/optimize/TestTransformPathFlatten.java
Labels: enhancement

#1616 calculate ungrounded path starting set lazily
  jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIter.java
  jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterExtendByVar.java
  jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterRepeatApply.java
  jena-arq/src/main/java/org/apache/jena/sparql/path/PathLib.java
  jena-arq/src/main/java/org/apache/jena/sparql/util/graph/GraphUtils.java
Labels: improvement

#1640 Further path flattening test coverage
  jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformPathFlattenAlgebra.java
  jena-arq/src/main/java/org/apache/jena/sparql/path/PathCompiler.java
  jena-arq/src/test/java/org/apache/jena/sparql/algebra/optimize/TestTransformPathFlatten.java
Labels: SPARQL
